#!/bin/bash

clear
rm -f cmd/voodoo

if [[ "$1" == "" ]]; then
	echo "No parameter supplied, I don't know what to do!"
	exit 1
fi

if [[ "$1" == "build" || "$1" == "run" ]]; then
	valid="true"
	echo Building...
	cd cmd
	go build voodoo.go
	cd ..
fi

if [[ "$1" == "run" ]]; then
	valid="true"
	echo Running...
	cd cmd
	./voodoo run scroll_1.voo
	cd ..
fi

if [[ "$valid" != "true" ]]; then
	echo "I don't understand the option '$1'..."
fi
